import Head from 'next/head'
import Image from 'next/image'

import Tooltips from '../components/Tooltip'

export default function About() {
  return (
    <>
      <Head>
        <title>Ahmad Atif | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/portfolio/favicon.ico" /> */}
        <link rel="apple-touch-icon" sizes="57x57" href="/portfolio/favicon/apple-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/portfolio/favicon/apple-icon-60x60.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/portfolio/favicon/apple-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/portfolio/favicon/apple-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/portfolio/favicon/apple-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/portfolio/favicon/apple-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/portfolio/favicon/apple-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/portfolio/favicon/apple-icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/portfolio/favicon/apple-icon-180x180.png" />
        <link rel="icon" type="image/png" sizes="192x192"  href="/portfolio/favicon/android-icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/portfolio/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="96x96" href="/portfolio/favicon/favicon-96x96.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/portfolio/favicon/favicon-16x16.png" />
        <link rel="manifest" href="/portfolio/favicon/manifest.json" />
        <meta name="msapplication-TileColor" content="#0369a1" />
        <meta name="msapplication-TileImage" content="/portfolio/favicon/ms-icon-144x144.png" />
        <meta name="theme-color" content="#0369a1" />
      </Head>

      <main className='w-full min-h-full'>
        <section className='text-center sm:text-start sm:min-h-screen flex flex-col justify-center items-center sm:py-10 py-5'>
          <p className='sm:text-4xl text-2xl font-bold mb-6'>Hi, I’m Ahmad. Nice to meet you.</p>
          
          <div className='max-w-3xl sm:text-base text-sm flex flex-col items-center text-center gap-4'>
            <p>Hello! My name is Ahmad and I enjoy creating things that live on the internet. During my time in university, I had a roommate who was studying computer science while I pursued a degree in civil engineering.</p>
            <p>Surprisingly, I found myself comprehending his programming endeavors more easily than the subjects in my own field. My curiosity grew, and I became captivated by his work, which sparked my own interest in creating beginner-level games using JavaScript.</p>
            <p>Upon graduation, I reluctantly followed the path of civil engineering but lacked the passion and motivation for it. However, everything changed when I landed an internship opportunity at a startup company. There, I quickly absorbed knowledge and honed my skills, ultimately becoming proficient in web development. From that point on, I have been continuously thriving and growing in this field.</p>
            <p>Here are a few technologies I’ve been working with recently:</p>
          </div>

          <div className='grid sm:grid-cols-6 grid-cols-2 gap-4 w-full sm:justify-between justify-center items-center text-center mt-10'>
            <div className='sm:w-28 sm:h-28 w-20 h-20 mx-auto relative group'>
              <Image src='/portfolio/logo/html.svg' alt='technology logo' fill className='relative z-10 bg-white grayscale group-hover:grayscale-0 transform transition' />
              <Tooltips title='HTML' />
            </div>

            <div className='sm:w-28 sm:h-28 w-20 h-20 mx-auto relative group'>
              <Image src='/portfolio/logo/css.svg' alt='technology logo' fill className='relative z-10 bg-white grayscale group-hover:grayscale-0 transform transition' />
              <Tooltips title='CSS' />
            </div>

            <div className='sm:w-28 sm:h-28 w-20 h-20 mx-auto relative group'>
              <Image src='/portfolio/logo/javascript.svg' alt='technology logo' fill className='relative z-10 bg-white grayscale group-hover:grayscale-0 transform transition' />
              <Tooltips title='JAVASCRIPT' />
            </div>

            <div className='sm:w-28 sm:h-28 w-20 h-20 mx-auto relative group'>
              <Image src='/portfolio/logo/react.svg' alt='technology logo' fill className='relative z-10 bg-white grayscale group-hover:grayscale-0 transform transition' />
              <Tooltips title='REACTJS' />
            </div>

            <div className='sm:w-28 sm:h-28 w-20 h-20 mx-auto relative group'>
              <Image src='/portfolio/logo/nodejs.svg' alt='technology logo' fill className='relative z-10 bg-white grayscale group-hover:grayscale-0 transform transition' />
              <Tooltips title='NODEJS' />
            </div>

            <div className='sm:w-28 sm:h-28 w-20 h-20 mx-auto relative group'>
              <Image src='/portfolio/logo/mongodb.svg' alt='technology logo' fill className='relative z-10 bg-white grayscale group-hover:grayscale-0 transform transition' />
              <Tooltips title='MONGODB' />
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
