import Head from 'next/head'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Navigation, Pagination } from 'swiper'
import 'swiper/css'
import "swiper/css/navigation"
import "swiper/css/pagination"

import Nextsix from '@/components/experience/Nextsix'
import Ifcon from '@/components/experience/Ifcon'

export default function Experience() {
  return (
    <>
      <Head>
        <title>Ahmad Atif | Web Developer & Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portfolio/favicon.ico" />
      </Head>

      <main className='w-full min-h-full relative'>
        <section className='text-center sm:text-start sm:min-h-screen sm:pt-[112px] flex flex-col justify-center items-center sm:pb-10 py-5'>
          <Swiper navigation={false} pagination={{ dynamicBullets: true, }} modules={[Pagination]} className="mySwiper w-full h-full !pb-16 cursor-pointer">
            <SwiperSlide className='!w-full !mr-0 !flex !flex-col !items-center'>
              <Nextsix />
            </SwiperSlide>

            <SwiperSlide className='!w-full !mr-0 !flex !flex-col !items-center'>
              <Ifcon />
            </SwiperSlide>
          </Swiper>
        </section>
      </main>
    </>
  )
}
