import Head from "next/head";
import Link from "next/link";

export default function Home() {
  // const ahmad = ['A', 'h', 'm', 'a', 'd', ' ', ' A', 't', 'i', 'f']
  const ahmad = ["A", "h", "m", "a", "d"];
  const atif = ["A", "t", "i", "f"];
  return (
    <>
      <Head>
        <title>Ahmad Atif | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/portfolio/favicon.ico" /> */}
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/portfolio/favicon/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/portfolio/favicon/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/portfolio/favicon/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/portfolio/favicon/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/portfolio/favicon/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/portfolio/favicon/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/portfolio/favicon/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/portfolio/favicon/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/portfolio/favicon/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/portfolio/favicon/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/portfolio/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/portfolio/favicon/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/portfolio/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/portfolio/favicon/manifest.json" />
        <meta name="msapplication-TileColor" content="#0369a1" />
        <meta
          name="msapplication-TileImage"
          content="/portfolio/favicon/ms-icon-144x144.png"
        />
        <meta name="theme-color" content="#0369a1" />
      </Head>

      <main className="w-full h-full">
        <section className="w-full h-full text-center sm:text-start flex flex-col justify-center sm:pt-20">
          <p className="text-lg mb-4">Hi, my name is</p>
          <div className="flex items-center sm:gap-5 gap-2 sm:justify-start justify-center">
            <div className="flex">
              {ahmad.map((name, i) => (
                <h1 className="md:text-8xl text-4xl font-bold leading-none mb-3 transition-all duration-700 hover:text-sky-700 sm:hover:-translate-y-3 hover:-translate-y-1">
                  {name}
                </h1>
              ))}
            </div>
            <div className="flex">
              {atif.map((name, i) => (
                <h1 className="md:text-8xl text-4xl font-bold leading-none mb-3 transition-all duration-700 hover:text-sky-700 hover:-translate-y-3">
                  {name}
                </h1>
              ))}
            </div>
          </div>
          {/* <h1 className='md:text-8xl text-4xl font-bold leading-none mb-3 transition-all duration-200 hover:text-sky-700 hover:scale-105'>Ahmad Atif</h1> */}
          <h1 className="md:text-6xl text-4xl font-bold leading-none mb-7 bg-gradient-to-r from-sky-600 via-sky-400 to-sky-900 inline-block text-transparent bg-clip-text sm:h-16 h-20">
            I love creating things for webs.
          </h1>

          <p className="max-w-2xl mb-8 sm:block hidden">
            As a software engineer, I specialize in creating exceptional digital
            experiences and occasionally doing design work. While working with 
            <Link
              href="https://www.sols247.org/"
              className="relative font-semibold transition-all duration-200 hover:text-[#F8BE15]"
              target="_blank"
            >
              {" "}SOLS Foundation{" "}
            </Link>
            on education websites, I prioritize accessibility and user-centered
            design.
          </p>

          <p className="max-w-2xl mb-2 sm:hidden font-light">
            As a software engineer, I specialize in creating exceptional digital
            experiences and occasionally doing design work.
          </p>
          <p className="max-w-2xl mb-6 sm:hidden font-light">
            While working with The Next Six Sdn Bhd on property websites, I
            prioritize accessibility and user-centered design.
          </p>

          <div className="flex items-center justify-start gap-6">
            <div className="h-16 w-16 rounded-full border"></div>
            <div className="h-16 w-16 rounded-full border"></div>
          </div>
          {/* <div>
            <button disabled className="px-6 py-3 rounded-xl border-2 whitespace-nowrap disabled:bg-slate-100 text-slate-300">My Resume Coming Soon</button>
          </div> */}
        </section>
      </main>
    </>
  );
}
